### PR TITLE
Aoc24

### PR DESCRIPTION
**Pull request by majunting**

### CODE REVIEW

**Comment by AzimMuradov** [comment]
@hsz I think this should be removed

**Comment by AzimMuradov** [comment]
@majunting This repository isn't for your solutions. Please, close this PR

**Comment by AzimMuradov** [comment]
@jsoberg

**Comment by jsoberg** [comment]
I don't have write access but I agree - @majunting this is a Template repository, so the intended usage is to create a new repository from it specifically for your solutions (from the green "Use this template" button on the repository's main page)

**Comment by majunting** [comment]
Sorry, it was a mistake on my side, I was intended to create a MR to the forked repo

**Pull request closed without merging**
